<?php
/**
 * StorePaymentMethodsLightningNetworkApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * StorePaymentMethodsLightningNetworkApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StorePaymentMethodsLightningNetworkApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete
     *
     * Remove store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete($store_id, $crypto_code)
    {
        $this->apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteWithHttpInfo($store_id, $crypto_code);
    }

    /**
     * Operation apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteWithHttpInfo
     *
     * Remove store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteWithHttpInfo($store_id, $crypto_code)
    {
        $returnType = '';
        $request = $this->apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteRequest($store_id, $crypto_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteAsync
     *
     * Remove store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteAsync($store_id, $crypto_code)
    {
        return $this->apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteAsyncWithHttpInfo($store_id, $crypto_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteAsyncWithHttpInfo
     *
     * Remove store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteAsyncWithHttpInfo($store_id, $crypto_code)
    {
        $returnType = '';
        $request = $this->apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteRequest($store_id, $crypto_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete'
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDeleteRequest($store_id, $crypto_code)
    {
        // verify the required parameter 'store_id' is set
        if ($store_id === null || (is_array($store_id) && count($store_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store_id when calling apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete'
            );
        }
        // verify the required parameter 'crypto_code' is set
        if ($crypto_code === null || (is_array($crypto_code) && count($crypto_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $crypto_code when calling apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete'
            );
        }

        $resourcePath = '/api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($store_id !== null) {
            $resourcePath = str_replace(
                '{' . 'storeId' . '}',
                ObjectSerializer::toPathValue($store_id),
                $resourcePath
            );
        }
        // path params
        if ($crypto_code !== null) {
            $resourcePath = str_replace(
                '{' . 'cryptoCode' . '}',
                ObjectSerializer::toPathValue($crypto_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod
     *
     * Get store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to fetch (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\LightningNetworkPaymentMethodData
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod($store_id, $crypto_code)
    {
        list($response) = $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodWithHttpInfo($store_id, $crypto_code);
        return $response;
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodWithHttpInfo
     *
     * Get store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to fetch (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\LightningNetworkPaymentMethodData, HTTP status code, HTTP response headers (array of strings)
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodWithHttpInfo($store_id, $crypto_code)
    {
        $returnType = '\Swagger\Client\Model\LightningNetworkPaymentMethodData';
        $request = $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodRequest($store_id, $crypto_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\LightningNetworkPaymentMethodData',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodAsync
     *
     * Get store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodAsync($store_id, $crypto_code)
    {
        return $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodAsyncWithHttpInfo($store_id, $crypto_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodAsyncWithHttpInfo
     *
     * Get store Lightning Network payment method
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodAsyncWithHttpInfo($store_id, $crypto_code)
    {
        $returnType = '\Swagger\Client\Model\LightningNetworkPaymentMethodData';
        $request = $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodRequest($store_id, $crypto_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod'
     *
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodRequest($store_id, $crypto_code)
    {
        // verify the required parameter 'store_id' is set
        if ($store_id === null || (is_array($store_id) && count($store_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store_id when calling storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod'
            );
        }
        // verify the required parameter 'crypto_code' is set
        if ($crypto_code === null || (is_array($crypto_code) && count($crypto_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $crypto_code when calling storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod'
            );
        }

        $resourcePath = '/api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($store_id !== null) {
            $resourcePath = str_replace(
                '{' . 'storeId' . '}',
                ObjectSerializer::toPathValue($store_id),
                $resourcePath
            );
        }
        // path params
        if ($crypto_code !== null) {
            $resourcePath = str_replace(
                '{' . 'cryptoCode' . '}',
                ObjectSerializer::toPathValue($crypto_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethods
     *
     * Get store Lightning Network payment methods
     *
     * @param  string $store_id The store to fetch (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\LightningNetworkPaymentMethodDataList
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethods($store_id)
    {
        list($response) = $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsWithHttpInfo($store_id);
        return $response;
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsWithHttpInfo
     *
     * Get store Lightning Network payment methods
     *
     * @param  string $store_id The store to fetch (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\LightningNetworkPaymentMethodDataList, HTTP status code, HTTP response headers (array of strings)
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsWithHttpInfo($store_id)
    {
        $returnType = '\Swagger\Client\Model\LightningNetworkPaymentMethodDataList';
        $request = $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsRequest($store_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\LightningNetworkPaymentMethodDataList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsAsync
     *
     * Get store Lightning Network payment methods
     *
     * @param  string $store_id The store to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsAsync($store_id)
    {
        return $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsAsyncWithHttpInfo($store_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsAsyncWithHttpInfo
     *
     * Get store Lightning Network payment methods
     *
     * @param  string $store_id The store to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsAsyncWithHttpInfo($store_id)
    {
        $returnType = '\Swagger\Client\Model\LightningNetworkPaymentMethodDataList';
        $request = $this->storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsRequest($store_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethods'
     *
     * @param  string $store_id The store to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethodsRequest($store_id)
    {
        // verify the required parameter 'store_id' is set
        if ($store_id === null || (is_array($store_id) && count($store_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store_id when calling storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethods'
            );
        }

        $resourcePath = '/api/v1/stores/{storeId}/payment-methods/LightningNetwork';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($store_id !== null) {
            $resourcePath = str_replace(
                '{' . 'storeId' . '}',
                ObjectSerializer::toPathValue($store_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod
     *
     * Update store Lightning Network payment method
     *
     * @param  \Swagger\Client\Model\LightningNetworkPaymentMethodData $body body (required)
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\LightningNetworkPaymentMethodData
     */
    public function storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod($body, $store_id, $crypto_code)
    {
        list($response) = $this->storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodWithHttpInfo($body, $store_id, $crypto_code);
        return $response;
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodWithHttpInfo
     *
     * Update store Lightning Network payment method
     *
     * @param  \Swagger\Client\Model\LightningNetworkPaymentMethodData $body (required)
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\LightningNetworkPaymentMethodData, HTTP status code, HTTP response headers (array of strings)
     */
    public function storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodWithHttpInfo($body, $store_id, $crypto_code)
    {
        $returnType = '\Swagger\Client\Model\LightningNetworkPaymentMethodData';
        $request = $this->storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodRequest($body, $store_id, $crypto_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\LightningNetworkPaymentMethodData',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodAsync
     *
     * Update store Lightning Network payment method
     *
     * @param  \Swagger\Client\Model\LightningNetworkPaymentMethodData $body (required)
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodAsync($body, $store_id, $crypto_code)
    {
        return $this->storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodAsyncWithHttpInfo($body, $store_id, $crypto_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodAsyncWithHttpInfo
     *
     * Update store Lightning Network payment method
     *
     * @param  \Swagger\Client\Model\LightningNetworkPaymentMethodData $body (required)
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodAsyncWithHttpInfo($body, $store_id, $crypto_code)
    {
        $returnType = '\Swagger\Client\Model\LightningNetworkPaymentMethodData';
        $request = $this->storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodRequest($body, $store_id, $crypto_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod'
     *
     * @param  \Swagger\Client\Model\LightningNetworkPaymentMethodData $body (required)
     * @param  string $store_id The store to fetch (required)
     * @param  string $crypto_code The crypto code of the payment method to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethodRequest($body, $store_id, $crypto_code)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod'
            );
        }
        // verify the required parameter 'store_id' is set
        if ($store_id === null || (is_array($store_id) && count($store_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store_id when calling storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod'
            );
        }
        // verify the required parameter 'crypto_code' is set
        if ($crypto_code === null || (is_array($crypto_code) && count($crypto_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $crypto_code when calling storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod'
            );
        }

        $resourcePath = '/api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($store_id !== null) {
            $resourcePath = str_replace(
                '{' . 'storeId' . '}',
                ObjectSerializer::toPathValue($store_id),
                $resourcePath
            );
        }
        // path params
        if ($crypto_code !== null) {
            $resourcePath = str_replace(
                '{' . 'cryptoCode' . '}',
                ObjectSerializer::toPathValue($crypto_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
