<?php
/**
 * InvoiceAdditionalStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * InvoiceAdditionalStatus Class Doc Comment
 *
 * @category Class
 * @description An additional status that describes why an invoice is in its current status.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoiceAdditionalStatus
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
const PAID_LATE = 'PaidLate';
const PAID_PARTIAL = 'PaidPartial';
const MARKED = 'Marked';
const INVALID = 'Invalid';
const PAID_OVER = 'PaidOver';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
self::PAID_LATE,
self::PAID_PARTIAL,
self::MARKED,
self::INVALID,
self::PAID_OVER,        ];
    }
}
