<?php
/**
 * CreateOnChainTransactionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateOnChainTransactionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateOnChainTransactionRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOnChainTransactionRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateOnChainTransactionRequest"
     */
    public function testCreateOnChainTransactionRequest()
    {
    }

    /**
     * Test attribute "destinations"
     */
    public function testPropertyDestinations()
    {
    }

    /**
     * Test attribute "fee_rate"
     */
    public function testPropertyFeeRate()
    {
    }

    /**
     * Test attribute "proceed_with_payjoin"
     */
    public function testPropertyProceedWithPayjoin()
    {
    }

    /**
     * Test attribute "proceed_with_broadcast"
     */
    public function testPropertyProceedWithBroadcast()
    {
    }

    /**
     * Test attribute "no_change"
     */
    public function testPropertyNoChange()
    {
    }

    /**
     * Test attribute "rbf"
     */
    public function testPropertyRbf()
    {
    }

    /**
     * Test attribute "selected_inputs"
     */
    public function testPropertySelectedInputs()
    {
    }
}
