<?php
/**
 * PaymentRequestsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PaymentRequestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentRequestsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for paymentRequestsArchivePaymentRequest
     *
     * Archive payment request.
     *
     */
    public function testPaymentRequestsArchivePaymentRequest()
    {
    }

    /**
     * Test case for paymentRequestsCreatePaymentRequest
     *
     * Create a new payment request.
     *
     */
    public function testPaymentRequestsCreatePaymentRequest()
    {
    }

    /**
     * Test case for paymentRequestsGetPaymentRequest
     *
     * Get payment request.
     *
     */
    public function testPaymentRequestsGetPaymentRequest()
    {
    }

    /**
     * Test case for paymentRequestsGetPaymentRequests
     *
     * Get payment requests.
     *
     */
    public function testPaymentRequestsGetPaymentRequests()
    {
    }

    /**
     * Test case for paymentRequestsUpdatePaymentRequest
     *
     * Update payment request.
     *
     */
    public function testPaymentRequestsUpdatePaymentRequest()
    {
    }
}
