<?php
/**
 * StorePaymentMethodsLightningNetworkApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * StorePaymentMethodsLightningNetworkApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StorePaymentMethodsLightningNetworkApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete
     *
     * Remove store Lightning Network payment method.
     *
     */
    public function testApiV1StoresStoreIdPaymentMethodsLightningNetworkCryptoCodeDelete()
    {
    }

    /**
     * Test case for storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod
     *
     * Get store Lightning Network payment method.
     *
     */
    public function testStoreLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethod()
    {
    }

    /**
     * Test case for storeLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethods
     *
     * Get store Lightning Network payment methods.
     *
     */
    public function testStoreLightningNetworkPaymentMethodsGetLightningNetworkPaymentMethods()
    {
    }

    /**
     * Test case for storeLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod
     *
     * Update store Lightning Network payment method.
     *
     */
    public function testStoreLightningNetworkPaymentMethodsUpdateLightningNetworkPaymentMethod()
    {
    }
}
